# Generated by Django 3.0.4 on 2020-03-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200314_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='related_id',
        ),
    ]
