# Generated by Django 3.0.4 on 2020-04-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('manager', 'manager'), ('lecture', 'lecture')], max_length=10)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
    ]
